name: Deploy

on:
  push:
    branches:
      - dev
      - master
      - prod

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GDBP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GDBP_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Generalized Deployments
        uses: brave-intl/general-docker-build-pipeline-action@v1
