name: Deploy

on:
  push:
    branches:
      - dev
      - master
      - prod

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
          aws-region: us-west-2
      - name: Generalized Deployments
        uses: brave-intl/general-docker-build-pipeline-action@b0863fef760c56e04a608d1b3018cf5bb01ca097 # v1.0.23
